/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook-16.glb -Tt 
Files: macbook-16.glb [639.28KB] > /home/ucok/Workspace/Coding Project/projects/( WORKING ) YT - JS Mastery - Master Creative Frontend in 2 Hours with React, Three.js & GSAP/macbook-gsap-landing/public/models/macbook-16-transformed.glb [629.72KB] (1%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { useEffect, type JSX } from "react";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { NO_CHANGE_PARTS } from "../../constants";
import { useMacbookStore } from "../../hooks/use-macbook-store";
import { isMeshWithMaterial } from "../../utils";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ActionName = any;

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_127: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    zhGRTuGrQoJflBD: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    lmWQsEjxpsebDlK: THREE.MeshStandardMaterial;
    LtEafgAVRolQqRw: THREE.MeshStandardMaterial;
    iyDJFXmHelnMTbD: THREE.MeshStandardMaterial;
    eJObPwhgFzvfaoZ: THREE.MeshStandardMaterial;
    nDsMUuDKliqGFdU: THREE.MeshStandardMaterial;
    CRQixVLpahJzhJc: THREE.MeshStandardMaterial;
    YYwBgwvcyZVOOAA: THREE.MeshStandardMaterial;
    SLGkCohDDelqXBu: THREE.MeshStandardMaterial;
    WnHKXHhScfUbJQi: THREE.MeshStandardMaterial;
    fNHiBfcxHUJCahl: THREE.MeshStandardMaterial;
    LpqXZqhaGCeSzdu: THREE.MeshStandardMaterial;
    gMtYExgrEUqPfln: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    JvMFZolVCdpPqjj: THREE.MeshStandardMaterial;
    sfCQkHOWyrsLmor: THREE.MeshStandardMaterial;
    ZCDwChwkbBfITSW: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Macbook16Model(props: JSX.IntrinsicElements["group"]) {
  const { color } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF(
    "/models/macbook-16-transformed.glb"
  ) as unknown as GLTFResult;

  const texture = useTexture("/screen.png");
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.needsUpdate = true;

  useEffect(() => {
    scene.traverse((child) => {
      if (isMeshWithMaterial(child)) {
        if (!NO_CHANGE_PARTS.includes(child.name)) {
          child.material.color = new THREE.Color(color);
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.zhGRTuGrQoJflBD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.PaletteMaterial002}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.lmWQsEjxpsebDlK}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.LtEafgAVRolQqRw}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.iyDJFXmHelnMTbD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.eJObPwhgFzvfaoZ}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.nDsMUuDKliqGFdU}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.CRQixVLpahJzhJc}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.YYwBgwvcyZVOOAA}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.SLGkCohDDelqXBu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.WnHKXHhScfUbJQi}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.fNHiBfcxHUJCahl}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.LpqXZqhaGCeSzdu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.gMtYExgrEUqPfln}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.PaletteMaterial003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_107.geometry}
        material={materials.JvMFZolVCdpPqjj}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Object_123.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshBasicMaterial map={texture} />
      </mesh>
      <mesh
        geometry={nodes.Object_127.geometry}
        material={materials.ZCDwChwkbBfITSW}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/macbook-16-transformed.glb");
